name: Build & test on macOS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 2" # At 00:00 every Tuesday

jobs:
  build_and_test_macos:
    name: "ci/run.sh on macOS"
    runs-on: macos-10.15
    env:
      # Disable progress bar in Cargo. This cuts down on output, avoiding log length limits.
      TERM: dumb
      TARGET: x86_64-apple-darwin

    strategy:
      fail-fast: false
      matrix:
        use_homebrew: [false, true]

    steps:
      - name: Install gettext from Homebrew
        if: ${{ matrix.use_homebrew }}
        run: |
          brew install gettext
          echo 'GETTEXT_DIR=/usr/local/opt/gettext' >> $GITHUB_ENV

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

        # setup-rust-action turns panic messages in tests into GitHub
        # annotations. Our test suite is running with --verbose, and prints out
        # messages even for panics that we do expect. setup-rust-action can't
        # know about this though, and floods the UI with annotations. This
        # command disables annotations for tests.
      - name: Disable GitHub Annotations
        run: echo '::remove-matcher owner=cargo-test::'

      - name: Check out the code
        uses: actions/checkout@v2

      - name: Generate lockfile
        run: cargo generate-lockfile

      - name: Cache Cargo dependencies
        uses: actions/cache@v2
        with:
          key: ${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/cache
            ~/.cargo/registry/index

      - name: ./ci/run.sh
        run: sh ci/run.sh
